### ISSUE TITLE
installDevice doesn't work for apk split project

### ISSUE THREAD

**Issue by beeender** [novoda/gradle-android-command-plugin#122]
gradle-android-command-plugin version `1.7.1`

If the Android project is using ABI split, `installDevice` task will always try to install arm64 ABI apk file.

To reproduce this, download the project in the attachment, connect a NON-ARM64 device (like an emulator), then run

```
./gradlew installDeviceDebug
```

output:
```
> Task :app:installDeviceDebug
==========================
Device[id:192.168.56.101:5555, sdk:25, version:7.1.1, brand:Android, manufacturer:Genymotion, model:Google Pixel - 7.1.0 - API 25 - 1080x1920, country:, language:, timezone:America/New_York]
==========================


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDeviceDebug'.
> Adb command failed with error:
  Failed to install /bigdick/home/cc/tmp/ABISplit/app/build/outputs/apk/debug/app-arm64-v8a-debug.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

```

Actually I don't quite understand the point of having `installDevice` task, doesn't the android plugin have a `install` task will do the same? Maybe this task should be removed and just make other tasks depend on the android plugin's `install` task?

[ABISplit.zip](https://github.com/novoda/gradle-android-command-plugin/files/1280244/ABISplit.zip)

**Comment by tasomaniac** [comment]
@beeender at the time the `installDevice` task was introduced, the official `install` task did not have configuration and just failed if you have multiple devices connected. Right now, it installs to all connected devices. 

Our task `installDevice` just installs to a specific device. First listed devices by default, and optionally configurable. 

This is basically a bug caused by assuming that the output can only have 1 APK. This should definitely be fixed.
