### ISSUE TITLE
Possible to call adb command anywhere in build script

### ISSUE THREAD

**Issue by tprochazka** [novoda/gradle-android-command-plugin#57]
Sometimes can be very usefull possibility to call adb command manually by build script,  without define task. Like this plugin https://github.com/michel-kraemer/gradle-download-task can do with `donwload {}` construct.

**Comment by devisnik** [comment]
:+1 We've started something like this with file handling, see 
https://github.com/novoda/gradle-android-command-plugin/blob/file_handling/gradle-android-command-plugin/src/main/groovy/com/novoda/gradle/command/Files.groovy

To be extended once we the file handling is merged.

**Comment by tasomaniac** [comment]
I have started to create DSLs for common tasks. They create tasks later than of course. 
But those tasks can be attached together with other tasks in gradle using `dependsOn` etc to achieve desired outcome. 

It's been a very long time since this issue is open. Please re-open it if this does not satisfy your needs.
