### ISSUE TITLE
Only install on current profile

### ISSUE THREAD

**Issue by jaredsburrows** [novoda/gradle-android-command-plugin#93]
I am seeing an issue on Lollipop and up, where the plugin installs the application for "all users". This forces me to do:

```
./gradlew uninstallAll
```

or manually go into the phones Settings and view the applications and manually "uninstall for all users".

**Comment by blundell** [comment]
@jaredsburrows as compared to what? Sorry I haven't looked into this multiuser support to much. What is the behaviour you expect? And do you have any docs/references hinting at what happens / what should happen?

**Comment by friedger** [comment]
@blundell http://stackoverflow.com/questions/20746422/how-to-use-adb-to-install-development-apps-for-one-user-only

Expected behaviour: app is only installed for current user
Current behaviour: app is installed globally.

It looks like there is no easy solution yet.

**Comment by jaredsburrows** [comment]
@friedger  Yes, thank you.

Basically, I have to uninstall the application twice via the "Applications" in the "Settings" menu or run `gradlew uninstallAll`.

**Comment by tasomaniac** [comment]
I noticed this issue as well. https://code.google.com/p/android/issues/detail?id=191519

I've tried myself. `adb shell pm install --user current [file_path]` works as expected. It only installs for the current user.

I think `adb install` just forwards all command line arguments. That's why `adb install --user current [file_path]` also worked for me. 

I tested this only with a Nougat emulator. I don't know if it will work for all devices.

Although it seems that the fix is just adding `--user current`, I don't know if we should do that by default. Considering the default behavior is to install for all users, it can lead to some unexpected behavior for some users. 

We can potentially support command line arguments that we pass to `adb` command.

**Comment by jaredsburrows** [comment]
@tasomaniac  Any update on this?

**Comment by tasomaniac** [comment]
No net yet. I stopped actively working on the project currently. After finishing my open PR I wanted to continue working in this area. Not just this, I want to reconsider how we do install tasks

**Comment by tasomaniac** [comment]
Sorry for getting back so late. This can actually be possible with custom tasks. Example below: 

```groovy
 task('installCurrentUser', com.novoda.gradle.command.Install) {
            customFlags = ['--user', 'current']
        }
```

Actually, I have been working on creating DSL for install tasks. Doing this will be easier. Something like this. 

```groovy
install {
  currentUser {
    customFlags = ['--user', 'current']
  }
}
```

or even better: 

```groovy
install {
  currentUser.customFlags = ['--user', 'current']
}
```

**Comment by jaredsburrows** [comment]
@tasomaniac Thanks!
